# stage1 - build react app first 
FROM node:14.16.0-alpine3.10 as build
WORKDIR /app_ui
ENV PATH /app/node_modules/.bin:$PATH
COPY ./package.json /app_ui/
COPY ./yarn.lock /app_ui/
RUN yarn
COPY . /app_ui
RUN yarn build

# stage 2 - build the final image and copy the react build files
FROM nginx:1.18.0-alpine
COPY --from=build /app_ui/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
